version: '3.8'

services:
  springboot:
    build: .  # Dockerfileを使ってビルド
    image: springboot:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["/app/wait-for-it.sh", "db:5432", "--", "java", "-jar", "/app/app.jar"]
    volumes:
      - ./build:/app/build

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JobPortal
      POSTGRES_DB: JobPortalDB
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db-store: