version: '3.8'

services:
  springboot:
    build: .
    image: springboot:latest
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/JobPortalDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: JobPortal
    depends_on:
      - db
    command: ["/app/wait-for-it.sh", "db:5432", "--", "java", "-jar", "/app/JobPortal-0.9.jar"]
    volumes:
      - ./build:/app/build

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JobPortal
      POSTGRES_DB: JobPortalDB
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db-store: